import 'package:flutter/cupertino.dart';

class Suggestion {
  Suggestion({this.icon, this.title, this.type, this.enable});

  Icon icon;
  String title;
  SuggestionType type;
  bool enable;
  static final suggestions = [
    Suggestion(type: SuggestionType.DIVIDER, title: 'File type', enable: false),
    Suggestion(
        type: SuggestionType.FILE,
        title: 'PDFs',
        icon: Icon(
          const IconData(0xf62d,
              fontFamily: CupertinoIcons.iconFont,
              fontPackage: CupertinoIcons.iconFontPackage),
          color: CupertinoColors.systemRed,
        ),
        enable: true),
    Suggestion(
        type: SuggestionType.FILE,
        title: 'Documents',
        icon: Icon(
          const IconData(0xf62d,
              fontFamily: CupertinoIcons.iconFont,
              fontPackage: CupertinoIcons.iconFontPackage),
          color: CupertinoColors.systemBlue,
        ),
        enable: true),
    Suggestion(
        type: SuggestionType.FILE,
        title: 'Spreadsheets',
        icon: Icon(
          const IconData(0xf62d,
              fontFamily: CupertinoIcons.iconFont,
              fontPackage: CupertinoIcons.iconFontPackage),
          color: CupertinoColors.systemGreen,
        ),
        enable: true),
    Suggestion(
        type: SuggestionType.FILE,
        title: 'Presentations',
        icon: Icon(
          const IconData(0xf62d,
              fontFamily: CupertinoIcons.iconFont,
              fontPackage: CupertinoIcons.iconFontPackage),
          color: CupertinoColors.systemYellow,
        ),
        enable: true),
    Suggestion(
        type: SuggestionType.DIVIDER, title: 'Date created', enable: false),
    Suggestion(
        type: SuggestionType.DATE_CREATED,
        title: 'Today',
        icon: Icon(
          const IconData(0xf5b0,
              fontFamily: CupertinoIcons.iconFont,
              fontPackage: CupertinoIcons.iconFontPackage),
        ),
        enable: true),
    Suggestion(
        type: SuggestionType.DATE_CREATED,
        title: 'Yesterday',
        icon: Icon(
          const IconData(0xf5b0,
              fontFamily: CupertinoIcons.iconFont,
              fontPackage: CupertinoIcons.iconFontPackage),
        ),
        enable: true),
    Suggestion(
        type: SuggestionType.DATE_CREATED,
        title: 'Last 7 days',
        icon: Icon(
          const IconData(0xf5b0,
              fontFamily: CupertinoIcons.iconFont,
              fontPackage: CupertinoIcons.iconFontPackage),
        ),
        enable: true),
    Suggestion(
        type: SuggestionType.DATE_CREATED,
        title: 'Last 30 days',
        icon: Icon(
          const IconData(0xf5b0,
              fontFamily: CupertinoIcons.iconFont,
              fontPackage: CupertinoIcons.iconFontPackage),
        ),
        enable: true),
    Suggestion(
        type: SuggestionType.DATE_CREATED,
        title: 'Last 90 days',
        icon: Icon(
          const IconData(0xf5b0,
              fontFamily: CupertinoIcons.iconFont,
              fontPackage: CupertinoIcons.iconFontPackage),
        ),
        enable: true),
    Suggestion(type: SuggestionType.DIVIDER, title: 'Owned by', enable: false),
    Suggestion(
        type: SuggestionType.DATE_CREATED,
        title: 'Owned by me',
        icon: Icon(
          const IconData(0xf748,
              fontFamily: CupertinoIcons.iconFont,
              fontPackage: CupertinoIcons.iconFontPackage),
          color: CupertinoColors.systemGreen,
        ),
        enable: true),
    Suggestion(
        type: SuggestionType.DATE_CREATED,
        title: 'Not owned by me',
        icon: Icon(
          const IconData(0xf74c,
              fontFamily: CupertinoIcons.iconFont,
              fontPackage: CupertinoIcons.iconFontPackage),
          color: CupertinoColors.systemGreen,
        ),
        enable: true),
  ];

  static final stringSuggestions = [
    'Đề thi toán cao cấp A1',
    'Đề thi toán cao cấp A2',
    'Đề thi toán cao cấp A3',
    'Đề thi xác xuất thống kê ứng dụng',
    'Đề thi xử lý ảnh',
    'Đề thi hóa phân tích',
    'Đề thi sức bền vật liệu',
    'Đề thi vật lý 1',
    'Đề thi vật lý 2',
    'Đề thi vật lý 3',
    'Đề thi giải tích 1',
    'Đề thi giải tích 2',
    'Đề thi toán rời rạc',
    'Đề thi kỹ thuật số',
    'Đề thi cơ lý thuyết',
    'Đề thi vi xử lý',
    'Đề thi anh văn 1',
    'Đề thi anh văn 2',
    'Đề thi anh văn 3',
    'Đề thi anh văn 4',
    'Đề thi anh văn 5',
    'Đề thi đại số tuyến tính',
    'Đề thi toán ứng dụng',
    'Đề thi toán cao cấp c1',
    'Đề thi toán cao cấp c2',
    'Đề thi toán cao cấp c3',
    'Đề thi phương pháp tính',
    'Đề thi điều khiển lập trình',
    'Đề thi ứng dụng matlab',
    'Khoa Lý luận Chính trị',
    'Khoa Khoa học ứng dụng',
    'Khoa Cơ khí Chế tạo máy',
    'Khoa Điện - Điện tử',
    'Khoa Cơ khí Động lực',
    'Khoa Kinh tế',
    'Khoa Công nghệ thông tin',
    'Khoa In và Truyền thông',
    'Khoa Công nghệ May và Thời Trang',
    'Khoa Công nghệ Hóa học và Thực phẩm',
    'Khoa Xây dựng',
    'Khoa Ngoại ngữ',
    'Khoa Đào tạo Chất lượng cao',
    'Viện Sư phạm Kỹ thuật',
    'Khoa Đào tạo Chất lượng cao',
    'Ngành CNKT điện, điện tử',
    'Ngành CNKT điện tử - viễn thông',
    'Ngành CNKT máy tính',
    'Ngành CNKT điều khiển và tự động hóa',
    'Ngành Kỹ thuật y sinh (Điện tử y sinh)',
    'Ngành Hệ thống nhúng và IoT',
    'Ngành Robot và trí tuệ nhân tạo',
    'Ngành CN chế tạo máy',
    'Ngành CNKT cơ điện tử',
    'Ngành CNKT cơ khí',
    'Ngành Kỹ thuật công nghiệp',
    'Ngành Kỹ nghệ gỗ và nội thất',
    'Ngành CNKT công trình xây dựng',
    'Ngành Kỹ thuật xây dựng công trình giao thông',
    'Ngành Quản lý xây dựng',
    'Ngành Hệ thống kỹ thuật công trình xây dựng',
    'Ngành CNKT ô tô',
    'Ngành CNKT nhiệt',
    'Ngành Năng lượng tái tạo',
    'Ngành CN thông tin',
    'Ngành Kỹ thuật dữ liệu',
    'Ngành Quản lý công nghiệp',
    'Ngành Kế toán',
    'Ngành Thương mại điện tử',
    'Ngành Logistics và quản lý chuỗi cung ứng',
    'Ngành Kinh doanh Quốc tế',
    'Ngành Công nghệ may',
    'Ngành CN Kỹ thuật in',
    'Ngành Thiết kế đồ họa',
    'Ngành Kiến trúc',
    'Ngành Kiến trúc nội thất',
    'Ngành Công nghệ vật liệu',
    'Ngành CNKT môi trường',
    'Ngành CN thực phẩm',
    'Ngành CNKT hóa học',
    'Ngành Quản trị NH và DV ăn uống',
    'Ngành Thiết kế thời trang',
    'Ngành Sư phạm tiếng Anh',
    'Ngành Ngôn ngữ Anh',
  ];
}

enum SuggestionType { DIVIDER, FILE, DATE_CREATED, OWNED }
